<?php
/**
 * 商品情報登録 API v1
 *
 */
// require("../common/config.php");
// require_once($CMS_PATH . '/wp-load.php'); // functionを読んでることになる
$parse_uri = explode( 'wp-content', $_SERVER['SCRIPT_FILENAME'] )[0];
require_once( $parse_uri . 'wp-load.php' );
require_once( $parse_uri . '/wp-content/themes/maker/assets/api/v1/common/data-operation.php' );
global $wpdb;

ini_set("memory_limit", "512M");

$json = file_get_contents("php://input");
$contents = json_decode($json, true);

// 商品情報を取得
$query = "WITH RankedMeta AS (
    SELECT
        wp_posts.ID,
        wp_postmeta.meta_key,
        wp_postmeta.meta_value,
        ROW_NUMBER() OVER(PARTITION BY wp_posts.ID, wp_postmeta.meta_key ORDER BY wp_postmeta.meta_value) AS rn
    FROM 
        wp_posts
    LEFT JOIN 
        wp_postmeta ON wp_posts.ID = wp_postmeta.post_id
    WHERE
        wp_posts.post_type = 'products'
        AND wp_postmeta.meta_key IN (
            'model_number',
            'product_price',
            'product_merit',
            'item_1',
            'item_2',
            'item_3',
            'item_4',
            'item_5',
            'item_6',
            'item_7',
            'item_8',
            'item_9',
            'item_10',
            'item_11',
            'item_12',
            'item_13',
            'item_14',
            'item_15',
            'item_16',
            'item_17',
            'item_18',
            'item_19',
            'item_name_1',
            'item_about_1',
            'item_name_2',
            'item_about_2',
            'item_name_3',
            'item_about_3',
            'item_name_4',
            'item_about_4',
            'item_name_5',
            'item_about_5',
            'document_name',
            'document_url',
            'document_link_blank',
            'product_color_name',
            'product_color_code',
            'color_model_number',
            'price_color_non_taxed',
            'color_file_1',
            'color_file_2',
            'color_file_3',
            'color_file_4',
            'color_file_5',
            'color_file_6',
            'color_file_7',
            'color_3d_movie_1',
            'color_3d_movie_thumbnail_1',
            'color_3d_movie_2',
            'color_3d_movie_thumbnail_2',
            'color_youtube_movie',
            'product_display_order',
            'product_image_pc',
            'product_image_sp'
        )
)
SELECT
    wp_posts.ID AS ID,
    wp_posts.post_title AS post_title,
    wp_posts.post_name AS post_name,
    wp_posts.post_status AS post_status,
    subquery.term_id AS term_id,
    subquery.term_name AS term_name,
    -- 仕様 19種+フリー入力欄5種
    MAX(CASE WHEN RankedMeta.meta_key = 'model_number' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS model_number,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_price' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS product_price,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_merit' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS product_merit,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_1' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_2' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_3' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_4' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_5' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_6' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_7' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_8' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_9' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_10' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_11' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_12' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_13' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_14' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_15' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_15,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_16' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_16,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_17' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_17,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_18' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_18,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_19' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_19,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_name_1' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_name_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_about_1' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_about_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_name_2' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_name_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_about_2' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_about_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_name_3' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_name_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_about_3' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_about_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_name_4' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_name_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_about_4' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_about_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_name_5' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_name_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'item_about_5' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS item_about_5,
    -- 関連資料 3種
    MAX(CASE WHEN RankedMeta.meta_key = 'document_name' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS document_name_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'document_url' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS document_url_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'document_link_blank' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS document_link_blank_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'document_name' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS document_name_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'document_url' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS document_url_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'document_link_blank' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS document_link_blank_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'document_name' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS document_name_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'document_url' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS document_url_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'document_link_blank' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS document_link_blank_3,
    -- カラー 14種
    -- カラー1
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS product_color_name_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS product_color_code_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS color_model_number_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS price_color_non_taxed_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS color_file_1_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS color_file_2_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS color_file_3_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS color_file_4_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS color_file_5_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS color_file_6_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS color_file_7_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS color_3d_movie_1_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS color_3d_movie_2_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_1,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS color_youtube_movie_1,
    -- カラー2
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS product_color_name_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS product_color_code_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS color_model_number_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS price_color_non_taxed_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS color_file_1_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS color_file_2_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS color_file_3_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS color_file_4_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS color_file_5_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS color_file_6_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS color_file_7_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS color_3d_movie_1_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS color_3d_movie_2_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_2,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 2 THEN RankedMeta.meta_value END) AS color_youtube_movie_2,
    -- カラー3
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS product_color_name_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS product_color_code_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS color_model_number_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS price_color_non_taxed_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS color_file_1_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS color_file_2_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS color_file_3_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS color_file_4_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS color_file_5_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS color_file_6_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS color_file_7_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS color_3d_movie_1_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS color_3d_movie_2_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_3,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 3 THEN RankedMeta.meta_value END) AS color_youtube_movie_3,
    -- カラー4
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS product_color_name_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS product_color_code_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS color_model_number_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS price_color_non_taxed_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS color_file_1_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS color_file_2_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS color_file_3_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS color_file_4_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS color_file_5_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS color_file_6_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS color_file_7_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS color_3d_movie_1_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS color_3d_movie_2_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_4,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 4 THEN RankedMeta.meta_value END) AS color_youtube_movie_4,
    -- カラー5
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS product_color_name_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS product_color_code_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS color_model_number_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS price_color_non_taxed_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS color_file_1_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS color_file_2_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS color_file_3_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS color_file_4_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS color_file_5_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS color_file_6_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS color_file_7_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS color_3d_movie_1_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS color_3d_movie_2_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_5,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 5 THEN RankedMeta.meta_value END) AS color_youtube_movie_5,
    -- カラー6
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS product_color_name_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS product_color_code_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS color_model_number_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS price_color_non_taxed_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS color_file_1_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS color_file_2_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS color_file_3_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS color_file_4_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS color_file_5_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS color_file_6_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS color_file_7_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS color_3d_movie_1_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS color_3d_movie_2_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_6,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 6 THEN RankedMeta.meta_value END) AS color_youtube_movie_6,
    -- カラー7
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS product_color_name_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS product_color_code_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS color_model_number_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS price_color_non_taxed_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS color_file_1_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS color_file_2_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS color_file_3_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS color_file_4_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS color_file_5_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS color_file_6_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS color_file_7_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS color_3d_movie_1_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS color_3d_movie_2_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_7,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 7 THEN RankedMeta.meta_value END) AS color_youtube_movie_7,
    -- カラー8
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS product_color_name_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS product_color_code_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS color_model_number_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS price_color_non_taxed_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS color_file_1_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS color_file_2_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS color_file_3_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS color_file_4_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS color_file_5_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS color_file_6_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS color_file_7_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS color_3d_movie_1_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS color_3d_movie_2_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_8,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 8 THEN RankedMeta.meta_value END) AS color_youtube_movie_8,
    -- カラー9
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS product_color_name_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS product_color_code_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS color_model_number_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS price_color_non_taxed_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS color_file_1_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS color_file_2_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS color_file_3_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS color_file_4_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS color_file_5_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS color_file_6_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS color_file_7_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS color_3d_movie_1_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS color_3d_movie_2_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_9,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 9 THEN RankedMeta.meta_value END) AS color_youtube_movie_9,
    -- カラー10
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS product_color_name_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS product_color_code_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS color_model_number_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS price_color_non_taxed_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS color_file_1_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS color_file_2_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS color_file_3_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS color_file_4_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS color_file_5_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS color_file_6_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS color_file_7_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS color_3d_movie_1_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS color_3d_movie_2_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_10,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 10 THEN RankedMeta.meta_value END) AS color_youtube_movie_10,
    -- カラー11
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS product_color_name_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS product_color_code_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS color_model_number_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS price_color_non_taxed_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS color_file_1_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS color_file_2_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS color_file_3_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS color_file_4_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS color_file_5_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS color_file_6_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS color_file_7_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS color_3d_movie_1_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS color_3d_movie_2_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_11,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 11 THEN RankedMeta.meta_value END) AS color_youtube_movie_11,
    -- カラー12
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS product_color_name_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS product_color_code_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS color_model_number_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS price_color_non_taxed_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS color_file_1_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS color_file_2_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS color_file_3_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS color_file_4_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS color_file_5_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS color_file_6_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS color_file_7_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS color_3d_movie_1_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS color_3d_movie_2_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_12,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 12 THEN RankedMeta.meta_value END) AS color_youtube_movie_12,
    -- カラー13
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS product_color_name_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS product_color_code_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS color_model_number_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS price_color_non_taxed_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS color_file_1_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS color_file_2_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS color_file_3_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS color_file_4_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS color_file_5_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS color_file_6_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS color_file_7_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS color_3d_movie_1_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS color_3d_movie_2_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_13,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 13 THEN RankedMeta.meta_value END) AS color_youtube_movie_13,
    -- カラー14
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_name' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS product_color_name_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_color_code' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS product_color_code_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_model_number' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS color_model_number_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'price_color_non_taxed' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS price_color_non_taxed_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_1' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS color_file_1_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_2' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS color_file_2_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_3' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS color_file_3_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_4' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS color_file_4_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_5' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS color_file_5_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_6' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS color_file_6_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_file_7' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS color_file_7_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_1' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS color_3d_movie_1_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_1' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_1_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_2' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS color_3d_movie_2_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_3d_movie_thumbnail_2' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS color_3d_movie_thumbnail_2_14,
    MAX(CASE WHEN RankedMeta.meta_key = 'color_youtube_movie' AND RankedMeta.rn = 14 THEN RankedMeta.meta_value END) AS color_youtube_movie_14,
    -- 一覧ページ設定
    MAX(CASE WHEN RankedMeta.meta_key = 'product_display_order' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS product_display_order,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_image_pc' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS product_image_pc,
    MAX(CASE WHEN RankedMeta.meta_key = 'product_image_sp' AND RankedMeta.rn = 1 THEN RankedMeta.meta_value END) AS product_image_sp
FROM 
    wp_posts
    LEFT JOIN (
        SELECT 
            wp_term_relationships.object_id, 
            wp_terms.term_id, 
            wp_terms.name AS term_name
        FROM 
            wp_terms
        LEFT JOIN 
            wp_term_relationships ON wp_terms.term_id = wp_term_relationships.term_taxonomy_id
        LEFT JOIN 
            wp_term_taxonomy ON wp_term_taxonomy.term_taxonomy_id = wp_term_relationships.term_taxonomy_id
        WHERE 
            wp_term_taxonomy.taxonomy = 'products-cat'
            ";
            // if (isset($_POST["p_parent_cat"]) && $_POST["p_parent_cat"] != 0) {
            //     $p_term_id = $_POST["p_parent_cat"];
            //     $p_terms = get_terms(
            //         'products-cat',
            //         array(
            //             'parent' => $p_term_id,
            //             'hide_empty' => false,
            //         ),
            //     );
            //     $query .= " AND wp_terms.term_id IN ".array_column($p_terms, 'term_id')."";
            // }
            $query .= "
    ) AS subquery ON wp_posts.ID = subquery.object_id
    LEFT JOIN RankedMeta ON wp_posts.ID = RankedMeta.ID
WHERE 
    wp_posts.post_type = 'products' AND wp_posts.post_status NOT IN ('auto-draft', 'trash')
GROUP BY
    wp_posts.ID,
    wp_posts.post_title,
    wp_posts.post_name,
    wp_posts.post_status,
    subquery.term_id,
    subquery.term_name;
";

// データ取得
// WPから商品情報取得
$productData = $wpdb->get_results($query);

// var_dump($_POST["p_parent_cat"]); // ネットワークで見れる
// var_dump($productData); // ネットワークで見れる

$returnProductData = json_decode(
    json_encode(
        array_values(
            $productData
        )
    ),
    true
);

// 出力方法
// 登録日順
// $result = json_encode(
//     array_values($productData)
// );
// jsonを返却
// if ($contents['outputCsv'] !== true) {
//     header("Content-Type: application/json; charset=utf-8");
//     echo $result;
//     exit;
// }

// CSVを返却、対象のカラム名
$csvTarget = [
    'ID',
    'post_title',
    'post_name',
    'post_status',
    'term_id',
    'term_name',
    'model_number',
    'product_price',
    'product_merit',
    'item_1',
    'item_2',
    'item_3',
    'item_4',
    'item_5',
    'item_6',
    'item_7',
    'item_8',
    'item_9',
    'item_10',
    'item_11',
    'item_12',
    'item_13',
    'item_14',
    'item_15',
    'item_16',
    'item_17',
    'item_18',
    'item_19',
    'item_name_1',
    'item_about_1',
    'item_name_2',
    'item_about_2',
    'item_name_3',
    'item_about_3',
    'item_name_4',
    'item_about_4',
    'item_name_5',
    'item_about_5',
    // カラー1
    'product_color_name_1',
    'product_color_code_1',
    'color_model_number_1',
    'price_color_non_taxed_1',
    'color_file_1_1',
    'color_file_2_1',
    'color_file_3_1',
    'color_file_4_1',
    'color_file_5_1',
    'color_file_6_1',
    'color_file_7_1',
    'color_3d_movie_1_1',
    'color_3d_movie_thumbnail_1_1',
    'color_3d_movie_2_1',
    'color_3d_movie_thumbnail_2_1',
    'color_youtube_movie_1',
    // カラー2
    'product_color_name_2',
    'product_color_code_2',
    'color_model_number_2',
    'price_color_non_taxed_2',
    'color_file_1_2',
    'color_file_2_2',
    'color_file_3_2',
    'color_file_4_2',
    'color_file_5_2',
    'color_file_6_2',
    'color_file_7_2',
    'color_3d_movie_1_2',
    'color_3d_movie_thumbnail_1_2',
    'color_3d_movie_2_2',
    'color_3d_movie_thumbnail_2_2',
    'color_youtube_movie_2',
    // カラー3
    'product_color_name_3',
    'product_color_code_3',
    'color_model_number_3',
    'price_color_non_taxed_3',
    'color_file_1_3',
    'color_file_2_3',
    'color_file_3_3',
    'color_file_4_3',
    'color_file_5_3',
    'color_file_6_3',
    'color_file_7_3',
    'color_3d_movie_1_3',
    'color_3d_movie_thumbnail_1_3',
    'color_3d_movie_2_3',
    'color_3d_movie_thumbnail_2_3',
    'color_youtube_movie_3',
    // カラー4
    'product_color_name_4',
    'product_color_code_4',
    'color_model_number_4',
    'price_color_non_taxed_4',
    'color_file_1_4',
    'color_file_2_4',
    'color_file_3_4',
    'color_file_4_4',
    'color_file_5_4',
    'color_file_6_4',
    'color_file_7_4',
    'color_3d_movie_1_4',
    'color_3d_movie_thumbnail_1_4',
    'color_3d_movie_2_4',
    'color_3d_movie_thumbnail_2_4',
    'color_youtube_movie_4',
    // カラー5
    'product_color_name_5',
    'product_color_code_5',
    'color_model_number_5',
    'price_color_non_taxed_5',
    'color_file_1_5',
    'color_file_2_5',
    'color_file_3_5',
    'color_file_4_5',
    'color_file_5_5',
    'color_file_6_5',
    'color_file_7_5',
    'color_3d_movie_1_5',
    'color_3d_movie_thumbnail_1_5',
    'color_3d_movie_2_5',
    'color_3d_movie_thumbnail_2_5',
    'color_youtube_movie_5',
    // カラー6
    'product_color_name_6',
    'product_color_code_6',
    'color_model_number_6',
    'price_color_non_taxed_6',
    'color_file_1_6',
    'color_file_2_6',
    'color_file_3_6',
    'color_file_4_6',
    'color_file_5_6',
    'color_file_6_6',
    'color_file_7_6',
    'color_3d_movie_1_6',
    'color_3d_movie_thumbnail_1_6',
    'color_3d_movie_2_6',
    'color_3d_movie_thumbnail_2_6',
    'color_youtube_movie_6',
    // カラー7
    'product_color_name_7',
    'product_color_code_7',
    'color_model_number_7',
    'price_color_non_taxed_7',
    'color_file_1_7',
    'color_file_2_7',
    'color_file_3_7',
    'color_file_4_7',
    'color_file_5_7',
    'color_file_6_7',
    'color_file_7_7',
    'color_3d_movie_1_7',
    'color_3d_movie_thumbnail_1_7',
    'color_3d_movie_2_7',
    'color_3d_movie_thumbnail_2_7',
    'color_youtube_movie_7',
    // カラー8
    'product_color_name_8',
    'product_color_code_8',
    'color_model_number_8',
    'price_color_non_taxed_8',
    'color_file_1_8',
    'color_file_2_8',
    'color_file_3_8',
    'color_file_4_8',
    'color_file_5_8',
    'color_file_6_8',
    'color_file_7_8',
    'color_3d_movie_1_8',
    'color_3d_movie_thumbnail_1_8',
    'color_3d_movie_2_8',
    'color_3d_movie_thumbnail_2_8',
    'color_youtube_movie_8',
    // カラー9
    'product_color_name_9',
    'product_color_code_9',
    'color_model_number_9',
    'price_color_non_taxed_9',
    'color_file_1_9',
    'color_file_2_9',
    'color_file_3_9',
    'color_file_4_9',
    'color_file_5_9',
    'color_file_6_9',
    'color_file_7_9',
    'color_3d_movie_1_9',
    'color_3d_movie_thumbnail_1_9',
    'color_3d_movie_2_9',
    'color_3d_movie_thumbnail_2_9',
    'color_youtube_movie_9',
    // カラー10
    'product_color_name_10',
    'product_color_code_10',
    'color_model_number_10',
    'price_color_non_taxed_10',
    'color_file_1_10',
    'color_file_2_10',
    'color_file_3_10',
    'color_file_4_10',
    'color_file_5_10',
    'color_file_6_10',
    'color_file_7_10',
    'color_3d_movie_1_10',
    'color_3d_movie_thumbnail_1_10',
    'color_3d_movie_2_10',
    'color_3d_movie_thumbnail_2_10',
    'color_youtube_movie_10',
    // カラー11
    'product_color_name_11',
    'product_color_code_11',
    'color_model_number_11',
    'price_color_non_taxed_11',
    'color_file_1_11',
    'color_file_2_11',
    'color_file_3_11',
    'color_file_4_11',
    'color_file_5_11',
    'color_file_6_11',
    'color_file_7_11',
    'color_3d_movie_1_11',
    'color_3d_movie_thumbnail_1_11',
    'color_3d_movie_2_11',
    'color_3d_movie_thumbnail_2_11',
    'color_youtube_movie_11',
    // カラー12
    'product_color_name_12',
    'product_color_code_12',
    'color_model_number_12',
    'price_color_non_taxed_12',
    'color_file_1_12',
    'color_file_2_12',
    'color_file_3_12',
    'color_file_4_12',
    'color_file_5_12',
    'color_file_6_12',
    'color_file_7_12',
    'color_3d_movie_1_12',
    'color_3d_movie_thumbnail_1_12',
    'color_3d_movie_2_12',
    'color_3d_movie_thumbnail_2_12',
    'color_youtube_movie_12',
    // カラー13
    'product_color_name_13',
    'product_color_code_13',
    'color_model_number_13',
    'price_color_non_taxed_13',
    'color_file_1_13',
    'color_file_2_13',
    'color_file_3_13',
    'color_file_4_13',
    'color_file_5_13',
    'color_file_6_13',
    'color_file_7_13',
    'color_3d_movie_1_13',
    'color_3d_movie_thumbnail_1_13',
    'color_3d_movie_2_13',
    'color_3d_movie_thumbnail_2_13',
    'color_youtube_movie_13',
    // カラー14
    'product_color_name_14',
    'product_color_code_14',
    'color_model_number_14',
    'price_color_non_taxed_14',
    'color_file_1_14',
    'color_file_2_14',
    'color_file_3_14',
    'color_file_4_14',
    'color_file_5_14',
    'color_file_6_14',
    'color_file_7_14',
    'color_3d_movie_1_14',
    'color_3d_movie_thumbnail_1_14',
    'color_3d_movie_2_14',
    'color_3d_movie_thumbnail_2_14',
    'color_youtube_movie_14',
    // 一覧ページ設定
    'product_display_order',
    'product_image_pc',
    'product_image_sp',
];

// 項目名
$csvHeader = [
    'ID',
    '商品名',
    '商品のパーマリンク',
    '公開・非公開',
    'カテゴリーのID',
    'カテゴリー名',
    '品番',
    '希望小売価格(税抜)',
    '特長',
    'スパウト',
    '対応穴径',
    '吐水',
    '回転範囲',
    '節湯',
    'JWWA',
    'サイズ',
    '材質',
    '設置タイプ',
    '排水口径',
    'オーバーフロー',
    '付属品',
    '引き棒',
    'ボウル深さ',
    '水栓取付穴径',
    '容量',
    '重量',
    '備考1',
    '備考2',
    '仕様１ 項目名',
    '仕様１ 概要',
    '仕様２ 項目名',
    '仕様２ 概要',
    '仕様３ 項目名',
    '仕様３ 概要',
    '仕様４ 項目名',
    '仕様４ 概要',
    '仕様５ 項目名',
    '仕様５ 概要',
    // カラー1
    'カラー1 カラー名',
    'カラー1 カラー設定',
    'カラー1 カラー別品番',
    'カラー1 カラー別希望小売価格(税抜)',
    'カラー1 画像１',
    'カラー1 画像２',
    'カラー1 画像３',
    'カラー1 画像４',
    'カラー1 画像５',
    'カラー1 画像６',
    'カラー1 画像７',
    'カラー1 動画・3Dモデル１',
    'カラー1 動画・3Dモデル１のサムネイル画像',
    'カラー1 動画・3Dモデル２',
    'カラー1 動画・3Dモデル２のサムネイル画像',
    'カラー1 youtube 動画URL',
    // カラー2
    'カラー2 カラー名',
    'カラー2 カラー設定',
    'カラー2 カラー別品番',
    'カラー2 カラー別希望小売価格(税抜)',
    'カラー2 画像１',
    'カラー2 画像２',
    'カラー2 画像３',
    'カラー2 画像４',
    'カラー2 画像５',
    'カラー2 画像６',
    'カラー2 画像７',
    'カラー2 動画・3Dモデル１',
    'カラー2 動画・3Dモデル１のサムネイル画像',
    'カラー2 動画・3Dモデル２',
    'カラー2 動画・3Dモデル２のサムネイル画像',
    'カラー2 youtube 動画URL',
    // カラー3
    'カラー3 カラー名',
    'カラー3 カラー設定',
    'カラー3 カラー別品番',
    'カラー3 カラー別希望小売価格(税抜)',
    'カラー3 画像１',
    'カラー3 画像２',
    'カラー3 画像３',
    'カラー3 画像４',
    'カラー3 画像５',
    'カラー3 画像６',
    'カラー3 画像７',
    'カラー3 動画・3Dモデル１',
    'カラー3 動画・3Dモデル１のサムネイル画像',
    'カラー3 動画・3Dモデル２',
    'カラー3 動画・3Dモデル２のサムネイル画像',
    'カラー3 youtube 動画URL',
    // カラー4
    'カラー4 カラー名',
    'カラー4 カラー設定',
    'カラー4 カラー別品番',
    'カラー4 カラー別希望小売価格(税抜)',
    'カラー4 画像１',
    'カラー4 画像２',
    'カラー4 画像３',
    'カラー4 画像４',
    'カラー4 画像５',
    'カラー4 画像６',
    'カラー4 画像７',
    'カラー4 動画・3Dモデル１',
    'カラー4 動画・3Dモデル１のサムネイル画像',
    'カラー4 動画・3Dモデル２',
    'カラー4 動画・3Dモデル２のサムネイル画像',
    'カラー4 youtube 動画URL',
    // カラー5
    'カラー5 カラー名',
    'カラー5 カラー設定',
    'カラー5 カラー別品番',
    'カラー5 カラー別希望小売価格(税抜)',
    'カラー5 画像１',
    'カラー5 画像２',
    'カラー5 画像３',
    'カラー5 画像４',
    'カラー5 画像５',
    'カラー5 画像６',
    'カラー5 画像７',
    'カラー5 動画・3Dモデル１',
    'カラー5 動画・3Dモデル１のサムネイル画像',
    'カラー5 動画・3Dモデル２',
    'カラー5 動画・3Dモデル２のサムネイル画像',
    'カラー5 youtube 動画URL',
    // カラー6
    'カラー6 カラー名',
    'カラー6 カラー設定',
    'カラー6 カラー別品番',
    'カラー6 カラー別希望小売価格(税抜)',
    'カラー6 画像１',
    'カラー6 画像２',
    'カラー6 画像３',
    'カラー6 画像４',
    'カラー6 画像５',
    'カラー6 画像６',
    'カラー6 画像７',
    'カラー6 動画・3Dモデル１',
    'カラー6 動画・3Dモデル１のサムネイル画像',
    'カラー6 動画・3Dモデル２',
    'カラー6 動画・3Dモデル２のサムネイル画像',
    'カラー6 youtube 動画URL',
    // カラー7
    'カラー7 カラー名',
    'カラー7 カラー設定',
    'カラー7 カラー別品番',
    'カラー7 カラー別希望小売価格(税抜)',
    'カラー7 画像１',
    'カラー7 画像２',
    'カラー7 画像３',
    'カラー7 画像４',
    'カラー7 画像５',
    'カラー7 画像６',
    'カラー7 画像７',
    'カラー7 動画・3Dモデル１',
    'カラー7 動画・3Dモデル１のサムネイル画像',
    'カラー7 動画・3Dモデル２',
    'カラー7 動画・3Dモデル２のサムネイル画像',
    'カラー7 youtube 動画URL',
    // カラー8
    'カラー8 カラー名',
    'カラー8 カラー設定',
    'カラー8 カラー別品番',
    'カラー8 カラー別希望小売価格(税抜)',
    'カラー8 画像１',
    'カラー8 画像２',
    'カラー8 画像３',
    'カラー8 画像４',
    'カラー8 画像５',
    'カラー8 画像６',
    'カラー8 画像７',
    'カラー8 動画・3Dモデル１',
    'カラー8 動画・3Dモデル１のサムネイル画像',
    'カラー8 動画・3Dモデル２',
    'カラー8 動画・3Dモデル２のサムネイル画像',
    'カラー8 youtube 動画URL',
    // カラー9
    'カラー9 カラー名',
    'カラー9 カラー設定',
    'カラー9 カラー別品番',
    'カラー9 カラー別希望小売価格(税抜)',
    'カラー9 画像１',
    'カラー9 画像２',
    'カラー9 画像３',
    'カラー9 画像４',
    'カラー9 画像５',
    'カラー9 画像６',
    'カラー9 画像７',
    'カラー9 動画・3Dモデル１',
    'カラー9 動画・3Dモデル１のサムネイル画像',
    'カラー9 動画・3Dモデル２',
    'カラー9 動画・3Dモデル２のサムネイル画像',
    'カラー9 youtube 動画URL',
    // カラー10
    'カラー10 カラー名',
    'カラー10 カラー設定',
    'カラー10 カラー別品番',
    'カラー10 カラー別希望小売価格(税抜)',
    'カラー10 画像１',
    'カラー10 画像２',
    'カラー10 画像３',
    'カラー10 画像４',
    'カラー10 画像５',
    'カラー10 画像６',
    'カラー10 画像７',
    'カラー10 動画・3Dモデル１',
    'カラー10 動画・3Dモデル１のサムネイル画像',
    'カラー10 動画・3Dモデル２',
    'カラー10 動画・3Dモデル２のサムネイル画像',
    'カラー10 youtube 動画URL',
    // カラー11
    'カラー11 カラー名',
    'カラー11 カラー設定',
    'カラー11 カラー別品番',
    'カラー11 カラー別希望小売価格(税抜)',
    'カラー11 画像１',
    'カラー11 画像２',
    'カラー11 画像３',
    'カラー11 画像４',
    'カラー11 画像５',
    'カラー11 画像６',
    'カラー11 画像７',
    'カラー11 動画・3Dモデル１',
    'カラー11 動画・3Dモデル１のサムネイル画像',
    'カラー11 動画・3Dモデル２',
    'カラー11 動画・3Dモデル２のサムネイル画像',
    'カラー11 youtube 動画URL',
    // カラー12
    'カラー12 カラー名',
    'カラー12 カラー設定',
    'カラー12 カラー別品番',
    'カラー12 カラー別希望小売価格(税抜)',
    'カラー12 画像１',
    'カラー12 画像２',
    'カラー12 画像３',
    'カラー12 画像４',
    'カラー12 画像５',
    'カラー12 画像６',
    'カラー12 画像７',
    'カラー12 動画・3Dモデル１',
    'カラー12 動画・3Dモデル１のサムネイル画像',
    'カラー12 動画・3Dモデル２',
    'カラー12 動画・3Dモデル２のサムネイル画像',
    'カラー12 youtube 動画URL',
    // カラー13
    'カラー13 カラー名',
    'カラー13 カラー設定',
    'カラー13 カラー別品番',
    'カラー13 カラー別希望小売価格(税抜)',
    'カラー13 画像１',
    'カラー13 画像２',
    'カラー13 画像３',
    'カラー13 画像４',
    'カラー13 画像５',
    'カラー13 画像６',
    'カラー13 画像７',
    'カラー13 動画・3Dモデル１',
    'カラー13 動画・3Dモデル１のサムネイル画像',
    'カラー13 動画・3Dモデル２',
    'カラー13 動画・3Dモデル２のサムネイル画像',
    'カラー13 youtube 動画URL',
    // カラー14
    'カラー14 カラー名',
    'カラー14 カラー設定',
    'カラー14 カラー別品番',
    'カラー14 カラー別希望小売価格(税抜)',
    'カラー14 画像１',
    'カラー14 画像２',
    'カラー14 画像３',
    'カラー14 画像４',
    'カラー14 画像５',
    'カラー14 画像６',
    'カラー14 画像７',
    'カラー14 動画・3Dモデル１',
    'カラー14 動画・3Dモデル１のサムネイル画像',
    'カラー14 動画・3Dモデル２',
    'カラー14 動画・3Dモデル２のサムネイル画像',
    'カラー14 youtube 動画URL',
    // 一覧ページ設定
    '表示順',
    '画像（PC）',
    '画像（スマホ）',
];
// $csvHeader = $csvTarget;

$csvData = [];
foreach ($returnProductData as $index => $productDataValue) {
    foreach ($csvTarget as $csvTargetValue) {
        $csvData[$index][] = strval($productDataValue[$csvTargetValue]);
    }
}
putCsv($csvHeader, $csvData);
